"""add description, change name to not unique

Revision ID: 5e84cd1fdcea
Revises: 
Create Date: 2022-08-18 00:00:26.104088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e84cd1fdcea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(length=80), nullable=True))
    op.drop_constraint('product_name_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_name_key', 'product', ['name'])
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
